# Generated by Django 6.0 on 2025-12-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
